//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public string idCustomerFeedback { get; set; }
        public string idOwner { get; set; }
        public string document { get; set; }
        public Nullable<int> quality { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Customer Customer1 { get; set; }
    }
}
