//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PropertyProjectEntities : DbContext
    {
        public PropertyProjectEntities()
            : base("name=PropertyProjectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<ExtraFee> ExtraFees { get; set; }
        public virtual DbSet<Feedback> Feedbacks { get; set; }
        public virtual DbSet<ImageProperty> ImageProperties { get; set; }
        public virtual DbSet<LegalDocument> LegalDocuments { get; set; }
        public virtual DbSet<PropertyPost> PropertyPosts { get; set; }
        public virtual DbSet<PropertyType> PropertyTypes { get; set; }
    }
}
