//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyPost
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PropertyPost()
        {
            this.ImageProperties = new HashSet<ImageProperty>();
            this.LegalDocuments = new HashSet<LegalDocument>();
        }
    
        public string idPost { get; set; }
        public string idCus { get; set; }
        public string propType { get; set; }
        public string propAddress { get; set; }
        public string city { get; set; }
        public string district { get; set; }
        public string wards { get; set; }
        public string street { get; set; }
        public string title { get; set; }
        public string nearby { get; set; }
        public int acreage { get; set; }
        public decimal price { get; set; }
        public string interior { get; set; }
        public string statusPost { get; set; }
        public string regulationTime { get; set; }
        public int bedRoom { get; set; }
        public int toilet { get; set; }
        public string animals { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImageProperty> ImageProperties { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LegalDocument> LegalDocuments { get; set; }
    }
}
